sudo: required
services:
  - docker
before_install:
  # The result of running $ travis encrypt-file service-account.json -r alejotem11/multi-k8s. Check the encrypt-file-ruby-docker.txt file
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  # **** Install Google Cloud SDK CLI **** #
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json